---

aws:

   account: 'ACCOUNT_ID' # as string

   partition: aws

   roles:

      app: NAME_OF_THE_APP_ROLE

      cloudformation: NAME_OF_THE_CLOUDFORMATION_ROLE

pipeline:

   cloudformation:

      # Pipeline stack template. CloudFormation stacks will be deployed from this template as-is
      template: cfn/pipeline.yaml

      stack:

         # Prefix for CloudFormation stack names
         # The pull request identifier will be appended
         name-prefix: pipeline-ORGANIZATION-REPOSITORY-

         # Tags for CloudFormation stacks
         tags:
            foo: bar
            Type: pipeline
