---

pipeline:

   cloudformation:

      # Pipeline stack template. CloudFormation stacks will be deployed from this template as-is
      template: cfn/pipeline.yaml

      stack:

         # Name pattern for CloudFormation stacks
         # See https://ruby-doc.org/stdlib-2.5.0/libdoc/erb/rdoc/ERB.html
         # for the template language (syntax, filters, etc.)
         # and https://pipeduct.io/docs/config
         # for the available variables.
         name: pipeline-{{ branch }}

         # Tags for the stack
         # The tag Manager=webpipe is automatically added
         tags:
            foo: bar
            Type: pipeline
