---

pipeline:

   cloudformation:

      # Pipeline stack template. CloudFormation stacks will be deployed from this template as-is
      template: cfn/pipeline.yaml

      stack:

         # Prefix for CloudFormation stack names
         # The pull request identifier will be appended
         name-prefix: pipeline-ORGANIZATION-REPOSITORY-

         # Tags for CloudFormation stacks
         tags:
            foo: bar
            Type: pipeline
